version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
